unsigned char ReadSPI(void);
void WriteSPI(unsigned int);
unsigned char ReadStatus(void);
void WriteEnable(void);
void WriteDisable(void);
void SPIWIPPolling(void);
void ByteWriteSPI(unsigned int, unsigned int, unsigned int, unsigned int);
unsigned char ByteReadSPI(unsigned char, unsigned char, unsigned char);
int save2memory(void);
void read_memory(void);
void format_memory(void);

void save_freq(unsigned long freq2tune,unsigned int vfo);
void save_ch(unsigned char ch);
void save_mod(unsigned char mod);
void save_echo(unsigned int echo);
void save_beep(unsigned int beep);
void save_led_br1(unsigned int led_br);
void save_led_br2(unsigned int led_br);
void save_led_color1(unsigned int led_color_v);
void save_led_color2(unsigned int led_color_v);
